[fix] fix for github action

diff --git a/.github/workflows/ios.yml b/.github/workflows/ios.yml
--- a/.github/workflows/ios.yml
+++ b/.github/workflows/ios.yml
@@ -19,8 +19,8 @@ jobs:
         env:
           GOOGLE_SERVICE_INFO_PLIST: ${{ secrets.GOOGLE_SERVICE_INFO_PLIST }}
         run: |
-          mkdir -p AnimeTracker
-          echo $GOOGLE_SERVICE_INFO_PLIST | base64 -d > AnimeTracker/GoogleService-Info.plist
+          mkdir -p AnimeTracker/AnimeTracker
+          echo $GOOGLE_SERVICE_INFO_PLIST | base64 -d > AnimeTracker/AnimeTracker/GoogleService-Info.plist
 
       - name: Set up Ruby
         uses: ruby/setup-ruby@v1
@@ -29,22 +29,22 @@ jobs:
           bundler-cache: true
 
       - name: Install CocoaPods
-        working-directory: AnimeTracker
+        working-directory: AnimeTracker/AnimeTracker
         run: |
           gem install cocoapods
           pod install
 
       - name: Debug Pod Install Output
         run: |
-          ls -l AnimeTracker/Pods/Target\ Support\ Files/GoogleAppMeasurement/ || echo "❌ GoogleAppMeasurement not found"
+          ls -l AnimeTracker/AnimeTracker/Pods/Target\ Support\ Files/GoogleAppMeasurement/ || echo "❌ GoogleAppMeasurement not found"
 
       - name: Cache CocoaPods
         uses: actions/cache@v4
         with:
           path: |
             ~/.cocoapods
-            AnimeTracker/Pods
-          key: ${{ runner.os }}-pods-${{ hashFiles('AnimeTracker/Podfile.lock') }}
+            AnimeTracker/AnimeTracker/Pods
+          key: ${{ runner.os }}-pods-${{ hashFiles('AnimeTracker/AnimeTracker/Podfile.lock') }}
           restore-keys: |
             ${{ runner.os }}-pods-
 
@@ -54,19 +54,21 @@ jobs:
           xcode-version: '16.2'
 
       - name: Build for testing
+        working-directory: AnimeTracker/AnimeTracker
         run: |
           xcodebuild build-for-testing \
-            -workspace AnimeTracker/AnimeTracker.xcworkspace \
+            -workspace AnimeTracker.xcworkspace \
             -scheme AnimeTracker \
             -configuration Release \
-            -xcconfig AnimeTracker/Config/Release.xcconfig \
+            -xcconfig Config/Release.xcconfig \
             -destination "platform=iOS Simulator,name=iPhone 16"
 
       - name: Run tests
+        working-directory: AnimeTracker/AnimeTracker
         run: |
           xcodebuild test-without-building \
-            -workspace AnimeTracker/AnimeTracker.xcworkspace \
+            -workspace AnimeTracker.xcworkspace \
             -scheme AnimeTracker \
             -configuration Release \
-            -xcconfig AnimeTracker/Config/Release.xcconfig \
+            -xcconfig Config/Release.xcconfig \
             -destination "platform=iOS Simulator,name=iPhone 16"
